//
// Created by KDIliev22 on 3/10/2025.
//

#ifndef MOVIE_TICKET_BOOKING_SYSTEM_10TH_GRADE_KDILIEV22_PAYMENTSERVICE_H
#define MOVIE_TICKET_BOOKING_SYSTEM_10TH_GRADE_KDILIEV22_PAYMENTSERVICE_H


class PaymentService {

};


#endif //MOVIE_TICKET_BOOKING_SYSTEM_10TH_GRADE_KDILIEV22_PAYMENTSERVICE_H
