//
// Created by KDIliev22 on 3/10/2025.
//

#ifndef MOVIE_TICKET_BOOKING_SYSTEM_10TH_GRADE_KDILIEV22_MENU_H
#define MOVIE_TICKET_BOOKING_SYSTEM_10TH_GRADE_KDILIEV22_MENU_H


class Menu {

};


#endif //MOVIE_TICKET_BOOKING_SYSTEM_10TH_GRADE_KDILIEV22_MENU_H
